name: "Pages"

on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
      - ".vitepress/**"
      - "package.json"
      - ".github/workflows/pages.yaml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Node 22"
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Install Dependencies"
        run: |
          npm install

      - name: "Build Documentation"
        run: npm run build

      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4
